<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Nonnas-MBP.domain" failures="1" tests="1" name="Create an account Test" time="27.723" errors="0" timestamp="16 Jan 2019 23:29:08 GMT">
  <testcase classname="positiveTC.CreateAnAccount" name="craeteAccount" time="14.564">
    <failure type="java.lang.AssertionError" message="We weren’t able to sign you up because there’s already an existing account for this email address. If you’ve forgotten your password, we’ll help to reset it expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: We weren’t able to sign you up because there’s already an existing account for this email address. If you’ve forgotten your password, we’ll help to reset it expected [true] but found [false]
	at positiveTC.CreateAnAccount.craeteAccount(CreateAnAccount.java:56)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- craeteAccount -->
</testsuite> <!-- Create an account Test -->
